from typing import TypedDict, Annotated, List
import operator

class AgentState(TypedDict):
    """
    The shared state of the agent graph.
    This acts as the 'Memory' that gets passed between the Planner and the Supervisor.
    """
    # The chat history (User input, Agent responses)
    # Annotated[..., operator.add] means new messages are APPENDED to the list, not overwritten
    messages: Annotated[List[dict], operator.add]
    
    # The Plan generated by the Planner (e.g., ["Fetch NVDA", "Chart it"])
    plan: List[str]
    
    # Flags for control flow
    is_ambiguous: bool       # True if we need to ask the user a question
    clarifying_question: str # The question to ask (if ambiguous)
    
    # The final output to show the user
    final_report: str
    
    # Charts generated during execution (Plotly figures)
    charts: List  # List of Plotly figure objects
    
    # Sources/citations from search results
    sources: List[dict]  # List of {title, url} dicts
