import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os
from pathlib import Path

def send_email(recipient: str, subject: str, body: str, attachments: list = None) -> str:
    """
    Sends an email using SMTP configuration from environment variables.
    
    Args:
        recipient: Email address to send to
        subject: Email subject line
        body: Email body (supports HTML)
        attachments: Optional list of file paths to attach
    
    Returns:
        Success/error message
    """
    # SMTP configuration from environment
    smtp_server = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("EMAIL_PORT", "587"))
    sender_email = os.getenv("EMAIL_USER")
    sender_password = os.getenv("EMAIL_PASSWORD")

    if not sender_email or not sender_password:
        return "Email not configured. Set EMAIL_USER and EMAIL_PASSWORD in .env file."

    try:
        # Create message
        msg = MIMEMultipart()
        msg['Subject'] = subject
        msg['From'] = sender_email
        msg['To'] = recipient

        # Add body as HTML
        msg.attach(MIMEText(body, 'html'))

        # Add attachments if provided
        if attachments:
            for file_path in attachments:
                if not os.path.exists(file_path):
                    continue
                    
                with open(file_path, 'rb') as f:
                    part = MIMEBase('application', 'octet-stream')
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        'Content-Disposition',
                        f'attachment; filename={Path(file_path).name}'
                    )
                    msg.attach(part)

        # Send email
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            # Log email details before sending
            print(f"[EMAIL DEBUG] Sending to: {recipient}")
            print(f"[EMAIL DEBUG] Subject: {subject}")
            print(f"[EMAIL DEBUG] Body Length: {len(body)} chars")
            print(f"[EMAIL DEBUG] Attachments: {attachments}")
            
            server.send_message(msg)
            
        attachment_info = f" with {len(attachments)} attachment(s)" if attachments else ""
        return f"Email sent to {recipient}{attachment_info}"
        
    except Exception as e:
        return f"Failed to send email: {str(e)}"


def format_report_html(title: str, content: str, sources: list = None) -> str:
    """
    Formats a financial report as HTML for email.
    
    Args:
        title: Report title
        content: Main report content (markdown will be converted)
        sources: Optional list of {title, url} dicts
    
    Returns:
        HTML string
    """
    # Convert markdown-style bold to HTML
    content_html = content.replace('**', '<strong>').replace('**', '</strong>')
    content_html = content_html.replace('\n', '<br>')
    
    sources_html = ""
    if sources:
        sources_html = "<h3>Sources</h3><ul>"
        for src in sources:
            sources_html += f"<li><a href='{src['url']}'>{src['title']}</a></li>"
        sources_html += "</ul>"
    
    html = f"""
    <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                h2 {{ color: #2c3e50; }}
                h3 {{ color: #34495e; margin-top: 20px; }}
                .header {{ background: #3498db; color: white; padding: 20px; }}
                .content {{ padding: 20px; }}
                .footer {{ background: #ecf0f1; padding: 10px; text-align: center; font-size: 12px; }}
                a {{ color: #3498db; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>{title}</h2>
            </div>
            <div class="content">
                {content_html}
                {sources_html}
            </div>
            <div class="footer">
                Generated by Multi-Agent Task Solver (Financial Domain)
            </div>
        </body>
    </html>
    """
    return html
